CREATE OR REPLACE TABLE PRIME_PROPERTIES_DW.ANALYTICS.STG_AGENTS (
    AGENT_ID STRING,
    AGENT_NAME STRING,
    COMMISSION_RATE FLOAT
);
CREATE OR REPLACE TABLE PRIME_PROPERTIES_DW.LANDING.STG_PROPERTIES (
    PROPERTY_ID STRING,
    PROPERTY_TYPE STRING, -- Apartment, House, Commercial
    CITY STRING,
    AREA STRING
);
CREATE OR REPLACE TABLE PRIME_PROPERTIES_DW.LANDING.STG_TRANSACTIONS (
    TRANSACTION_ID STRING,
    TRANSACTION_DATE DATE,
    PROPERTY_ID STRING,
    AGENT_ID STRING,
    CLIENT_NAME STRING,
    TRANSACTION_TYPE STRING, -- Sale / Rent
    AMOUNT NUMBER(15, 2)
);
CREATE OR REPLACE FILE FORMAT PRIME_PROPERTIES_DW.LANDING.CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    NULL_IF = ('NULL', 'null')
    EMPTY_FIELD_AS_NULL = TRUE;
    CREATE OR REPLACE TABLE PRIME_PROPERTIES_DW.LANDING.STG_AGENTS (
    AGENT_ID STRING,
    AGENT_NAME STRING,
    COMMISSION_RATE FLOAT
);
SELECT 'Agents' as Table_Name, COUNT(*) FROM PRIME_PROPERTIES_DW.LANDING.STG_AGENTS
UNION ALL
SELECT 'Properties', COUNT(*) FROM PRIME_PROPERTIES_DW.LANDING.STG_PROPERTIES
UNION ALL
SELECT 'Transactions', COUNT(*) FROM PRIME_PROPERTIES_DW.LANDING.STG_TRANSACTIONS;
-- 1. Agent Dimension banana
CREATE OR REPLACE TABLE PRIME_PROPERTIES_DW.ANALYTICS.DIM_AGENT AS
SELECT AGENT_ID, AGENT_NAME, COMMISSION_RATE
FROM PRIME_PROPERTIES_DW.LANDING.STG_AGENTS;

-- 2. Property Dimension banana
CREATE OR REPLACE TABLE PRIME_PROPERTIES_DW.ANALYTICS.DIM_PROPERTY AS
SELECT PROPERTY_ID, PROPERTY_TYPE, CITY, AREA
FROM PRIME_PROPERTIES_DW.LANDING.STG_PROPERTIES;

-- 3. Fact Table banana (Isme hum JOIN laga kar Commission calculate karenge)
CREATE OR REPLACE TABLE PRIME_PROPERTIES_DW.ANALYTICS.FACT_TRANSACTIONS AS
SELECT 
    T.TRANSACTION_ID,
    T.TRANSACTION_DATE,
    T.PROPERTY_ID,
    T.AGENT_ID,
    T.TRANSACTION_TYPE,
    T.AMOUNT,
    -- Calculation: Amount ko Agent ke rate se multiply karna
    (T.AMOUNT * A.COMMISSION_RATE) AS COMMISSION_EARNED 
FROM PRIME_PROPERTIES_DW.LANDING.STG_TRANSACTIONS T
JOIN PRIME_PROPERTIES_DW.LANDING.STG_AGENTS A ON T.AGENT_ID = A.AGENT_ID;
-- Check karein ke data Fact table mein calculations ke sath aaya ya nahi
SELECT * FROM PRIME_PROPERTIES_DW.ANALYTICS.FACT_TRANSACTIONS;

-- 1. Agent Performance Query
SELECT 
    A.AGENT_NAME, 
    SUM(F.AMOUNT) as TOTAL_REVENUE,
    COUNT(F.TRANSACTION_ID) as TOTAL_DEALS
FROM PRIME_PROPERTIES_DW.ANALYTICS.FACT_TRANSACTIONS F
JOIN PRIME_PROPERTIES_DW.ANALYTICS.DIM_AGENT A ON F.AGENT_ID = A.AGENT_ID
GROUP BY A.AGENT_NAME
ORDER BY TOTAL_REVENUE DESC;

-- 1. Pehle ye run karein (highlight karke Ctrl+Enter dabayein)
CREATE OR REPLACE TABLE PRIME_PROPERTIES_DW.ANALYTICS.DIM_AGENT AS
SELECT AGENT_ID, AGENT_NAME, COMMISSION_RATE
FROM PRIME_PROPERTIES_DW.LANDING.STG_AGENTS;

-- 2. Phir ye run karein
CREATE OR REPLACE TABLE PRIME_PROPERTIES_DW.ANALYTICS.DIM_PROPERTY AS
SELECT PROPERTY_ID, PROPERTY_TYPE, CITY, AREA
FROM PRIME_PROPERTIES_DW.LANDING.STG_PROPERTIES;

-- 3. Phir ye Fact table wali query dobara run karein
CREATE OR REPLACE TABLE PRIME_PROPERTIES_DW.ANALYTICS.FACT_TRANSACTIONS AS
SELECT 
    T.TRANSACTION_ID,
    T.TRANSACTION_DATE,
    T.PROPERTY_ID,
    T.AGENT_ID,
    T.TRANSACTION_TYPE,
    T.AMOUNT,
    (T.AMOUNT * A.COMMISSION_RATE) AS COMMISSION_EARNED 
FROM PRIME_PROPERTIES_DW.LANDING.STG_TRANSACTIONS T
JOIN PRIME_PROPERTIES_DW.LANDING.STG_AGENTS A ON T.AGENT_ID = A.AGENT_ID;
SELECT 
    A.AGENT_NAME, 
    SUM(F.AMOUNT) as TOTAL_REVENUE,
    COUNT(F.TRANSACTION_ID) as TOTAL_DEALS
FROM PRIME_PROPERTIES_DW.ANALYTICS.FACT_TRANSACTIONS F
JOIN PRIME_PROPERTIES_DW.ANALYTICS.DIM_AGENT A ON F.AGENT_ID = A.AGENT_ID
GROUP BY A.AGENT_NAME
ORDER BY TOTAL_REVENUE DESC;
SELECT 
    A.AGENT_NAME, 
    SUM(F.AMOUNT) as TOTAL_REVENUE,
    COUNT(F.TRANSACTION_ID) as TOTAL_DEALS
FROM PRIME_PROPERTIES_DW.ANALYTICS.FACT_TRANSACTIONS F
JOIN PRIME_PROPERTIES_DW.ANALYTICS.DIM_AGENT A ON F.AGENT_ID = A.AGENT_ID
GROUP BY A.AGENT_NAME
ORDER BY TOTAL_REVENUE DESC;
SELECT 
    A.AGENT_NAME, 
    SUM(F.AMOUNT) as TOTAL_SALES_VOLUME,
    SUM(F.COMMISSION_EARNED) as TOTAL_COMMISSION_PAID,
    ROUND(AVG(F.AMOUNT), 2) as AVG_DEAL_SIZE
FROM PRIME_PROPERTIES_DW.ANALYTICS.FACT_TRANSACTIONS F
JOIN PRIME_PROPERTIES_DW.ANALYTICS.DIM_AGENT A ON F.AGENT_ID = A.AGENT_ID
GROUP BY A.AGENT_NAME
ORDER BY TOTAL_COMMISSION_PAID DESC;